# Generated by Django 5.2.1 on 2025-06-21 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='instructor_applications/resumes/')),
                ('cover_letter', models.TextField(help_text='Tell us why you want to become an instructor and your teaching experience.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Application',
                'verbose_name_plural': 'Instructor Applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
