# Generated by Django 5.2.1 on 2025-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
