# Generated by Django 5.2.1 on 2025-06-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_completed',
        ),
    ]
